[package]
name = "prc_iron_gcd"
version = "0.1.0"
authors = ["Volodymyr Khytskyi <khytsky.vladimir@gmail.com>"]
edition = "2018"

[dependencies]
iron = "0.6.0"
mime = "0.2.3"
router = "0.6.0"
urlencoded = "0.6.0"